services:
- type: web
  name: server
  runtime: image
  image:
    url: twentycrm/twenty:latest
  dockerCommand: "sh -c ./scripts/render-run.sh"
  autoDeploy: false
  plan: standard
  envVars:
    - key: ACCESS_TOKEN_SECRET
      generateValue: true
    - key: LOGIN_TOKEN_SECRET
      generateValue: true
    - key: REFRESH_TOKEN_SECRET
      generateValue: true
    - key: PG_DATABASE_HOST
      fromService:
        name: twenty_postgres
        type: pserv
        property: host
    - key: PG_DATABASE_PORT
      fromService:
        name: twenty_postgres
        type: pserv
        property: port
  disk:
    name: twenty-disk
    mountPath: /.local-storage
    sizeGB: 5
- type: pserv
  name: twenty_postgres
  plan: starter
  runtime: image
  image:
    url: twentycrm/twenty-postgres:latest
  autoDeploy: false
  disk:
    name: data
    mountPath: /var/lib/postgresql/data
    sizeGB: 10
  envVars:
  - key: POSTGRES_USER
    value: postgres
  - key: POSTGRES_PASSWORD
    value: postgres
  - key: POSTGRES_DB
    value: default
